In [3]:
import torch
print(torch.__version__)

2.6.0+cu124


In [4]:
# Creating tensor
# The first thing we're going to create a scalar
# A scalar is a single number and in tensor-speak it's a zero dimension tensor

# Scalar

scalar = torch.tensor(4)
print(scalar)

tensor(4)


In [5]:
# We can check the dimension of a tensor using the '.ndim' attribute

scalar.ndim

0

In [9]:
# Get the  Python number within a tensor (only works with one-element tensor)
scalar.item()

4

In [10]:
# A vector is a single dimension tensor but can contain many nunbers.

# Vector
vector = torch.tensor([4, 5])
vector

tensor([4, 5])

In [12]:
# Check the number of dimensions of vector
vector.ndim

1

In [13]:
# Ckeck shape of vector
vector.shape

torch.Size([2])

In [15]:
# The above returns torch.Size([2]) which means our vector has a shape of [2].
# This is because of the two elements we placed inside the square brackets ([4, 5]).

In [18]:
# Matrix

matrix = torch.tensor([[4, 5],
                       [6, 7]])
matrix

tensor([[4, 5],
        [6, 7]])

In [19]:
# Check number of dimensions
matrix.ndim

2

In [21]:
matrix.shape

torch.Size([2, 2])

In [23]:
# Create a Tensor

tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [24]:
# Check number of dimension for TENSOR
tensor.ndim

3

In [25]:
# Check shape of TENSOR
tensor.shape

torch.Size([1, 3, 3])

In [29]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)
print(random_tensor.dtype)

tensor([[0.3367, 0.1943, 0.7391, 0.6355],
        [0.5307, 0.8971, 0.2867, 0.1182],
        [0.2463, 0.0042, 0.4769, 0.1306]])
torch.float32


In [30]:
# The flexibility of 'torch.rand()' is that we can adjust the size to be whatever we want.
# For example, say you wanted a random tensor in the common image shape of [244, 244, 3] ([height, width, color_channels]).

# Create a random tensor of size (244, 244, 3)

random_image_size_tensor = torch.rand(size=(244, 244, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [34]:
random_image_size_tensor

tensor([[[0.2668, 0.7737, 0.7976],
         [0.1873, 0.5850, 0.3034],
         [0.8531, 0.6511, 0.5750],
         ...,
         [0.9988, 0.2379, 0.7996],
         [0.0838, 0.6527, 0.4217],
         [0.1693, 0.1253, 0.3408]],

        [[0.5212, 0.7270, 0.1282],
         [0.3035, 0.3243, 0.6058],
         [0.5777, 0.8957, 0.1483],
         ...,
         [0.9122, 0.0875, 0.3040],
         [0.4997, 0.5119, 0.9425],
         [0.5470, 0.5288, 0.3401]],

        [[0.6255, 0.9809, 0.9492],
         [0.1923, 0.2986, 0.5894],
         [0.2673, 0.2469, 0.8117],
         ...,
         [0.4532, 0.0315, 0.9211],
         [0.9199, 0.7751, 0.4234],
         [0.6252, 0.5909, 0.4306]],

        ...,

        [[0.3950, 0.2668, 0.8732],
         [0.5123, 0.1844, 0.0619],
         [0.4751, 0.8323, 0.9728],
         ...,
         [0.8192, 0.7288, 0.6087],
         [0.3882, 0.7826, 0.4032],
         [0.3431, 0.5877, 0.0904]],

        [[0.7620, 0.1715, 0.2231],
         [0.1069, 0.9291, 0.8106],
         [0.

In [35]:
# Zeros and ones

In [49]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(5, 5))
print(zeros)
print(zeros.dtype)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.float32


In [51]:
# Create a tensor of all ones

ones = torch.ones(size=(5, 5))
print(ones)
print(ones.dtype)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
torch.float32


In [59]:
# Create a range of values 0 to 20 using 'torch.arange()'

zero_to_twenty = torch.arange(0, 20, 1)
zero_to_twenty

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [60]:
twenty_zeros = torch.zeros_like(zero_to_twenty)
twenty_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
print(twenty_zeros.shape)
print(twenty_zeros.size()) # '.shape' and '.size' are same ???

torch.Size([20])
torch.Size([20])


In [72]:
# Tensor Datatypes
# The most common type is (torch.float32 OR torch.float).
# But there's also 16-bit floating point (torch.float16 OR torch.half)
# And 64-bit floating point (torch.float64 OR torch.double)
# And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

In [74]:
# Defalt datatype for tensors is float32

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,# defaults to None, whice is 'torch.float32'
                               device=None, # defaults to None, whice uses the defaults tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded
print(float_32_tensor.shape)
print(float_32_tensor.dtype)
print(float_32_tensor.device)

torch.Size([3])
torch.float32
cpu


In [82]:
# Create a tensor with 'dtype=torch.float16'.
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [89]:
# shape - what shape is the tensor? (some operations require specific shape rules)
# dtype - what datatype are the elements within the tensor stored in?
# device - what device is the tensor stored on? (usually GPU or CPU)
# Let's create a random tensor and find out details about it.

In [96]:
# Create a tensor
some_tensor = torch.rand(6, 9)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.2729, 0.2778, 0.4827, 0.9926, 0.8588, 0.5509, 0.3613, 0.1985, 0.3425],
        [0.7425, 0.8663, 0.9048, 0.0511, 0.6067, 0.8102, 0.3561, 0.2663, 0.9193],
        [0.0132, 0.3389, 0.5439, 0.1989, 0.2606, 0.5589, 0.8170, 0.9834, 0.9978],
        [0.8411, 0.6814, 0.3165, 0.3861, 0.1156, 0.5136, 0.0864, 0.7615, 0.7307],
        [0.6886, 0.2349, 0.5980, 0.0731, 0.3948, 0.3472, 0.9892, 0.9810, 0.4567],
        [0.5957, 0.0058, 0.8578, 0.2680, 0.2445, 0.6345, 0.4524, 0.7889, 0.0920]])
Shape of tensor: torch.Size([6, 9])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [97]:
# Manipulating tensors (tensor operations)

In [98]:
# In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

# A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

# These operations are often a wonderful dance between:

# Addition
# Substraction
# Multiplication (element-wise)
# Division
# Matrix multiplication
# And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

# Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

In [99]:
# Basic operations
# Let's start with a few of the fundamental operations, addition (+), subtraction (-), mutliplication (*).
# They work just as you think they would.

In [100]:
# Create atensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [101]:
# Multiply it by 10
tensor * 10 # OR you can use PyTorch function like 'torch.multiply(tensor, 10)'.

tensor([10, 20, 30])

In [105]:
# Notice how the tensor values above didn't end up being tensor([110, 120, 130]),
# this is because the values inside the tensor don't change unless they're reassigned.

In [107]:
tensor

tensor([1, 2, 3])

In [108]:
# Let's subtract a number and this time we'll reassign the tensor variable.

In [109]:
# Subtract and reassing
# Like this
tensor = tensor - 10 # OR you can use PyTorch function like 'torch.subtract(tensor, 10)'
tensor

tensor([-9, -8, -7])

In [110]:
# Add and reassing
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [111]:
# PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplication) and torch.add() to perform basic operations.

In [117]:
# Can also use torch functions
torch.multiply(tensor, 10)
# OR
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [118]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [120]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [121]:
# Matrix multiplication (is all you need)

In [123]:
# The inner dimensions must match:
# (3, 2) @ (3, 2) won't work
# (2, 3) @ (3, 2) will work
# (3, 2) @ (2, 3) will work
# The resulting matrix has the shape of the outer dimensions:
# (2, 3) @ (3, 2) -> (2, 2)
# (3, 2) @ (2, 3) -> (3, 3)
# Note: "@" in Python is the symbol for matrix multiplication.

In [124]:
# Element-wise matrix multiplication
tensor * tensor # [1*1, 2*2, 3*3] = [1, 4, 9]

tensor([1, 4, 9])

In [126]:
# Matrix multiplication
torch.matmul(tensor, tensor) # [1*1 + 2*2 + 3*3] = [14]

tensor(14)

In [129]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [130]:
# You can do matrix multiplication by hand but it's not recommended.

# The in-built torch.matmul() method is faster.

%%time
# Matrix multiplication by hand
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 950 µs, sys: 994 µs, total: 1.94 ms
Wall time: 11.2 ms


tensor(14)

In [133]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 333 µs, sys: 0 ns, total: 333 µs
Wall time: 273 µs


tensor(14)

One of the most common errors in deep learning (shape errors)


In [136]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # this will error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [137]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [139]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [140]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [142]:
# You can also use 'torch.mm()' which is a short for 'torch.matmul()'
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [143]:
torch.manual_seed(42)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2,
                         out_features=6)

x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n Output shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)
 Output shape: torch.Size([3, 6])


In [147]:
tensor_A

2

In [ ]:
# torch.nn.Linear(in_features, out_features, bias=True) # Defalt bias=True

output = weight @ input + bias

In [3]:
import torch

In [4]:
import torch.nn as nn

# Create a linear layer with 3 input features and 5 output features
linear_layer = nn.Linear(in_features=3, out_features=5)

# Input data (shape: [batch_size, 3])
input_data = torch.randn(10, 3)  # Batch size of 10

# Pass the input data through the linear layer
output_data = linear_layer(input_data)

# Output data will have shape: [batch_size, 5]
print(output_data.shape)  # Output: torch.Size([10, 5])

torch.Size([10, 5])
